/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mail;

import mail.client.Mail;
import mail.client.SendClient;
import mail.client.imap.ImapClient;
import org.junit.Test;
import org.mockito.Mockito;

import java.io.BufferedReader;
import java.io.StringReader;

public class AppTest {


    @Test
    public void sendByRun() throws Exception {
        //given
        SendClient sendClient = Mockito.mock(SendClient.class);
        ImapClient imapClient = Mockito.mock(ImapClient.class);
        var app = new App(sendClient, imapClient);
        var input = new BufferedReader(new StringReader("message\nbody\n\n"));

        //when
        app.run(input, "send", "-to", "john@doe.com", "-s", "subject");

        //then
        var expected = new Mail("smtpmail@onet.pl", "john@doe.com", "subject", "message\nbody");
        Mockito.verify(sendClient).send(expected);
    }


}
